name=MyLedIO
version=1.0.0
author=Hanzeel Villa
maintainer=Hanzeel Villa <hanzeelvilla0@gmail.com>
sentence=Simple LED control library.
paragraph=A lightweight library to manage a single LED pin on Arduino boards. Includes init, on/off, and state tracking.
category=Signal Input/Output
url=https://github.com/hanzeelvilla/MyLedIO
architectures=*